# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf
# env = GSK_RENDERER,gl
