monitorv2 {
    output = desc:LG Electronics LG HDR 4K 0x0004B7BD
    mode = 3840x2160@60.0
    position = 0x0
    scale = 1.5
    bitdepth = 10
    vrr = 1
    cm = dcip3
    #supports_hdr = 1
    #min_luminance = 20
    #max_luminance = 300
    #sdr_min_luminance = 1
    #sdr_max_luminance = 400
    #sdrsaturation = 0.7
}

monitorv2 {
    output = desc:Samsung Electric Company S24F350 H4ZN800216
    mode = 1920x1080@72.0
    position = 2560x180
    scale = 1.0
    bitdepth = 10
    vrr = 1
    cm = dcip3
}

monitorv2 {
    output = desc:Samsung Electric Company S24F350 H4ZN718035
    mode = 1920x1080@72.0
    position = -1920x180
    scale = 1.0
    bitdepth = 10
    vrr = 1
    cm = dcip3
}

monitorv2 {
    output = vnc
    mode = 2880x1620@60
    position = 0x-2000
    scale = 1
}

monitor = , preferred, auto, 1
