[general]
tearing-mode = true

[bar]
scale = 0.800000011920929
background-opacity = 20
button-variant = "basic"

[[bar.layout]]
monitor = "DP-1"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "cpu",
    "ram",
    "storage",
    "netstat",
]
center = ["window-title"]
right = [
    "media",
    "volume",
    "bluetooth",
    "network",
    "hyprsunset",
    "systray",
    "notifications",
    "clock",
    "power",
]

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "hyprland-workspaces",
    "cpu",
    "ram",
    "storage",
    "netstat",
]
center = ["window-title"]
right = [
    "volume",
    "bluetooth",
    "network",
    "systray",
    "notifications",
    "clock",
    "power",
]

[modules.cava]
bars = 40
style = "wave"

[modules.clock]
format = "%a %b %d %H:%M:%S"
dropdown-show-seconds = true

[modules.cpu]
poll-interval-ms = 200
temp-sensor = ""
format = "{{ percent }}% {{ temp_c }}C @{{ avg_freq_ghz }}GHz"

[modules.dashboard]
right-click = "ulauncher-toggle"
dropdown-lock-command = "hyprlock"
dropdown-logout-command = "uwsm stop"

[modules.hyprland-workspaces]
app-icons-show = true

[modules.netstat]
poll-interval-ms = 1000

[modules.power]
left-click = "wlogout"

[modules.ram]
poll-interval-ms = 200
format = "{{ used_gib }}/{{ total_gib }} GiB"

[modules.storage]
format = "{{ used_gib }}/{{ total_gib }} GiB"

[modules.volume]
right-click = "pavucontrol"
middle-click = "helvum"

[osd]
position = "top"

[wallpaper]
engine-enabled = false
