#    ___       __           __           __
#   / _ |__ __/ /____  ___ / /____ _____/ /_
#  / __ / // / __/ _ \(_-</ __/ _ `/ __/ __/
# /_/ |_\_,_/\__/\___/___/\__/\_,_/_/  \__/
#

# Start Listeners
exec-once = uwsm app -- ~/.config/ml4w/listeners.sh --startall

# Start Polkit
exec-once= /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Restore Wallpaper
exec-once = uwsm app -- ~/.config/ml4w/scripts/ml4w-wallpaper-app --restore

# Autostart script
exec-once = uwsm app -- ~/.config/ml4w/scripts/ml4w-autostart

# Load GTK settings
exec-once = uwsm app -- ~/.config/hypr/scripts/gtk.sh

# Using hypridle to start hyprlock
exec-once = uwsm app -- hypridle

# Load cliphist history
exec-once = uwsm app -- wl-paste --watch cliphist store

# Autostart ML4W App
exec-once = uwsm app -- ~/.config/ml4w/scripts/ml4w-autostart.sh

# Start autostart cleanup
exec-once = uwsm app -- ~/.config/hypr/scripts/cleanup.sh

# Load configuration from ML4W Hyprland Settings App
exec = ~/.config/com.ml4w.hyprlandsettings/hyprctl.sh

exec-once = uwsm app -- wayle shell
exec-once = uwsm app -- hyprctl output create headless vnc
exec-once = uwsm app -- wayvnc -g -o vnc 0.0.0.0
exec-once = uwsm app -- ~/.config/wayvnc/event-watcher.sh

exec-once = ulauncher

exec-once = uwsm app -- ~/.config/pipewire/scripts/volumecontrol.py
exec-once = uwsm app -- hyprpm reload
