# Add your additional Hyprland configurations here
#
# This is an additional key binding
# bind = $mainMod CTRL, up, workspace, empty
#
# Example for xwayland
# xwayland {
#   force_zero_scaling = true
# }

# qt5ct environment variable
# env = QT_QPA_PLATFORMTHEME,qt5ct

# SDL version
env = SDL_VIDEODRIVER,wayland
# env = SDL_VIDEODRIVER,x11

# No Hardware Cursor
cursor {
    no_hardware_cursors = false
}
render {
    direct_scanout = 1
    cm_auto_hdr = 2
}
experimental {
    #xx_color_management_v4 = true
}
# Blur for waybar
#layerrule = blur, waybar
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = border_size 0, float 0, match:workspace w[tv1]
windowrule = rounding 0, float 0, match:workspace w[tv1]
windowrule = border_size 0, float 0, match:workspace f[1]
windowrule = rounding 0, float 0, match:workspace f[1]
debug {
    full_cm_proto=true
}
#for libadwaita gtk4 apps you can use this command:
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons
#you will need to set dark theme for qt apps from kde more difficult thans with gnome :D:
env = QT_QPA_PLATFORMTHEME,qt6ct   # for Qt apps# Theme
windowrule = immediate 1, float 1, size 607 1080, match:class gamescope

windowrule = float 1, size 562 1000, match:class Waydroid

# General Rules (Workspace, Float, No Decorations)
# This uses the common regex to match all 6 VMs.
windowrule = workspace 10, float 1, decorate 0, rounding 0, opaque 1, no_shadow 1, no_dim 1, match:title ^(QEMU \(vm[1-6]\))$

# --- Individual Placement Rules (3 columns, 2 rows) ---
# Each VM requires two separate rules for size and move.

# VM 1: Top Left (X=0, Y=0)
windowrule = size 640 540, move 0 0, match:title ^(QEMU \(vm1\))$
# VM 2: Top Middle (X=640, Y=0)
windowrule = size 640 540, move 640 0, match:title ^(QEMU \(vm2\))$
# VM 3: Top Right (X=1280, Y=0)
windowrule = size 640 540, move 1280 0, match:title ^(QEMU \(vm3\))$
# VM 4: Bottom Left (X=0, Y=540)
windowrule = size 640 540, move 0 540, match:title ^(QEMU \(vm4\))$
# VM 5: Bottom Middle (X=640, Y=540)
windowrule = size 640 540, move 640 540, match:title ^(QEMU \(vm5\))$
# VM 6: Bottom Right (X=1280, Y=540)
windowrule = size 640 540, move 1280 540, match:title ^(QEMU \(vm6\))$

#ulauncher rules
windowrule = float 1, pin 1, stay_focused 1, decorate 0, no_blur 1, xray 1, no_shadow 1, match:class ulauncher