#    __  _____  _____      __  _____          ___
#   /  |/  / / / / / | /| / / / ___/__  ___  / _/
#  / /|_/ / /_/_  _/ |/ |/ / / /__/ _ \/ _ \/ _/
# /_/  /_/____//_/ |__/|__/  \___/\___/_//_/_/
#

# Pavucontrol floating
windowrule = float 1, size 700 600, center 1, pin 1,match:class (.*org.pulseaudio.pavucontrol.*)

# Waypaper
windowrule = float 1, size 900 700, center 1, pin 1, match:class (.*waypaper.*)

# Newelle
windowrule = match:class (io.github.qwersyk.Newelle), float on, size 1000 700, center on, pin on

# ML4W Calendar
windowrule = match:class (com.ml4w.calendar), float on, move (50%-200) 85, pin on, size 400 400

# ML4W Sidebar
windowrule = match:class (com.ml4w.sidebar), float on, move (100%-window_w-18) 91, pin on, size 400 660

# ML4W Welcome App
windowrule = match:class (com.ml4w.welcome), float on, size 700 600, center on, pin on

# ML4W Settings App
windowrule = match:class (com.ml4w.settings), float on, size 800 600, move 10% 20%

# Blueman Manager
windowrule = match:class (blueman-manager), float on, size 800 600, center on

# nwg-look
windowrule = match:class (nwg-look), float on, size 700 600, move 10% 20%, pin on

# nwg-displays
windowrule = match:class (nwg-displays), float on, size 900 600, move 10% 20%, pin on

# System Mission Center
windowrule = match:class (io.missioncenter.MissionCenter), float on, pin on, center on, size 900 600

# System Mission Center Preference Window
windowrule = match:class (missioncenter), match:title ^(Preferences)$, float on, pin on, center on

# Gnome Calculator
windowrule = match:class (org.gnome.Calculator), float on, size 700 600, center on

# Hyprland Share Picker
windowrule = match:class (hyprland-share-picker), float on, pin on, center on, size 600 400

# General floating
windowrule = match:class (dotfiles-floating), float on, size 1000 700, center on

# Dotfiles Sidepad
windowrule = match:class (dotfiles-sidepad), float on, size 1000 700, center on, pin on

# Float and center file pickers
windowrule = match:class xdg-desktop-portal-gtk, match:title ^(Open.*Files?|Save.*Files?|All Files|Save)$, float on, center on

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# QT
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# GDK
env = GDK_SCALE,1

# Toolkit Backend
env = GDK_BACKEND,wayland,x11,*
env = CLUTTER_BACKEND,wayland

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Set the cursor size for xcursor
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# XWayland
xwayland {
  force_zero_scaling = true
}